### PR TITLE
Conservation space changes contributed back

### PR DESCRIPTION
**Pull request by radpet**
Properly add and destroy annotation tooltip events and try avoid memory leaks

@rsinghal @aeschylus @beaudet

This is a fix for https://github.com/ProjectMirador/mirador/issues/1320 plus the start of aligning ConservationSpace fork and official mirador repo.

### CODE REVIEW

**Comment by radpet** [comment]
The scalebar pr https://github.com/ProjectMirador/mirador/pull/1306 is included here

**Comment by mejackreed** [comment]
Is it possible to get the OpenSeaDragon Scalebar plugin added to npm and integrated that way? I'm not sure if that is maintained anymore: 

https://github.com/usnistgov/OpenSeadragonScalebar/issues/6

But if we want to include it in core Mirador, do we also want to take on maintenance?

**Comment by jbaiter** [comment]
I would also be up to working on integrating [our ruler plugin](https://github.com/dbmdz/mirador-plugins#physical-document-ruler) into core Mirador, it doesn't use the scalebar plugin and I would be willing to take on maintenance for it. It might be better suited for Mirador's current core use cases than the scalebar.

**Comment by radpet** [comment]
@mejackreed I tried adding it as node js module but as far as I remember npm had problems downloading it from git without auth for some reason. As I see it is not maintained but I suggest using it for the time @jbaiter 's plugin is up and working :).

**Comment by beaudet** [comment]
For awareness and information only, there is another ticket related to automatic synchronization of pan/zoom between slots that has a design description (no drawings yet I think) that suggests involving a ruler.  It's #223 and might be valuable for anyone implementing ruler type components.  You might also want to ping @markmatney regarding UCLALibrary's ruler implementation.

**Comment by markmatney** [comment]
@beaudet is right, no drawings (however, the feature is implemented on our [fork](https://github.com/UCLALibrary/mirador), and I did a [screencast](https://drive.google.com/file/d/0B_xDW0hVa9VzQU5UWUhPQ3BkWGs/view) a while back)

fwiw, our ruler implementation is a fork of [OpenSeadragonScalebar](https://github.com/usnistgov/OpenSeadragonScalebar)

**Comment by radpet** [comment]
This pull request https://github.com/ProjectMirador/mirador/pull/1380 includes all this fixes and adds the layers functionality on top of them, feel free to choose which one you would like to merge :)

**Comment by aeschylus** [comment]
This has quite a bit of overlap with #1380, so closing now.

Keep this PR in mind when integrating the many Ruler threads, along with #223

**Pull request closed without merging**
