### PR TITLE
1668 normalize state

### PR DESCRIPTION
**Pull request by charbugs**
Main reason for this PR is to normalize the window reducer as described in #1668. But it takes changes in 13 files to get all tests pass. For me, this shows the strong coupling of the existing code base and stresses the importance of a clear concept for the state layout.

### CODE REVIEW

**Comment by charbugs** [comment]
The PR doesn't pass the coverage test. But it's not clear to me why. If i check the details it complains about a file that I didn't touch. Could anyone ease the restrictions? @mejackreed perhaps?

**Comment by mejackreed** [comment]
I'm 👍 to easing the restrictions here and can merge.

@charbugs can you rebase on master to resolve the conflicts?

**Comment by jkeck** [comment]
I've noticed that code coverage can be a bit tricky in cases like this.  It might even be that you've reduced code (:tada:), some of which was tested, and that caused a total test coverage reduction.

In these cases I think we can be pragmatic about the coverage failures when the intent/testing of the code meets the community expectations/guidelines.

**Comment by mejackreed** [comment]
For clarity, we are going to force push a version of this branch up including only the needed commits by @charbugs.

**Pull request merged**
