### PR TITLE
#2287: replace selection list by simple list for change theme dialog

### LINKED ISSUE #2287: Update the "Settings" dialog to be "Change theme"
Related to #2286 

The current implementation uses a select list for the two theme options. We want to change this to use the [simple dialogs](https://material-ui.com/demos/dialogs/#simple-dialogs) approach, where we can instead present the options in a simple list:

theme

Also, the theme switcher dialog is currently triggered by the **Settings** workspace menu choice. We have changes to the workspace menus planned that we'll present in the near future, but for now, we should just rename the **Settings** menu choice to **Change theme** and that will trigger the Change theme dialog:

theme-menu

### Details
- Remove icon from "Settings" menu item
- Change label of "Settings" menu item to "Change theme"
- Rename title of dialog to "Change theme"
- Replace select list with simple list of the two theme options, using the [simple dialogs](https://material-ui.com/demos/dialogs/#simple-dialogs) approach
- Icon for both options is `@material-ui/icons/PaletteSharp`
- Icon colors: the dark version is `#000000` and the light version is `#BDBDBD`
- When the user mouses over or keyboards to one of the options, it gets the item highlighting background, as seen in the [simple dialogs demo](https://material-ui.com/demos/dialogs/#simple-dialogs):

theme-highlighted

### PR DESCRIPTION
**Pull request by glefi**
Closes #2287

### CODE REVIEW

**Comment by ggeisler** [comment]
@glefi Nice start on this. I'm not sure if this PR is intended to be complete or a work-in-progress but here are a couple of minor issues that should be updated, in case you are not already aware of them:

- The title heading for the dialog window should use Headline 2 typography defined in #2093, rather than the `H6` it currently uses. (This was noted in the [dialog story ticket](https://github.com/ProjectMirador/mirador/issues/2286).)

Some things that don't match the component demo at https://material-ui.com/demos/dialogs/#simple-dialogs but should:
- Hover highlighting as you move over the different theme options
- Cursor should be the hand cursor when highlighting any part of the theme options; currently it shows a pointer cursor when hovering over the icon and changes to a selection cursor when hovering over the theme option text
- The dialog should close automatically when selecting an option; currently the theme changes when selecting an option but the dialog doesn't close until you click again

Also, the dialog doesn't seem accessible via keyboard?

**Comment by glefi** [comment]
@ggeisler Thanks for your feedback. The dialog should now meet all the requirements. It would be nice if you could take another look at it.

**Comment by ggeisler** [comment]
Yep, the Change theme dialog looks good to me.

**Comment by ggeisler** [comment]
Just to be clear, my comments above on this PR were for only the Change theme dialog, not the Select workspace type dialog.

@glefi I assume you know that the Change workspace type dialog still needs:

- Adding the SVG icons I pointed you to
- Showing highlighting for the currently active workspace type

The latter issue does work in the Change theme dialog but last I saw when you open the Change workspace type dialog it does not show any highlighted for the currently selected type.

**Pull request merged**
