### PR TITLE
Set up Less to compile mirador.css

### LINKED ISSUE #104: Automate css namespacing so ours won't conflict with embed hosts.
It is annoying and error prone to write css while namespacing everything. A lot of our css is not namespaced because we never talked about conventions surrounding it in the beginning.

As long as we're compiling a larger stylesheet out of several anyway, we might as well pass it through a pre-compile process (or use LESS). This would also allow us to more transparently represent an actual style guide for the interface.

### PR DESCRIPTION
**Pull request by gigamorph**
See #1264 

Closes #104

### CODE REVIEW

**Comment by aeschylus** [comment]
@gigamorph Thank you so much for this. This is going to be much more pleasant to work on now. It looks like there are some conflicts generated by the move to 2.2 as the development branch. Can you look into these? They should just have to do with github getting confused by the .gitignore and current css files.

**Comment by gigamorph** [comment]
Interesting. I've only changed css, Gruntfile,and package.json and the coverage decreased.

**Comment by gigamorph** [comment]
I have resolved the conflict. The file structure might be open to discussion and change. I deleted and ignored mirador.css because it isn't meant to be edited directly.

If you haven't seen it yet, I had some more comments about this PR at #1264.

**Comment by csbailey5t** [comment]
@gigamorph The refactor looks great. Rather than requiring the user to change their markup, could you write a bit of JS to add the necessary class (`.mirador-container`) to the `#viewer` div? While it's a minor change, it would prevent an upgrade from immediately breaking installs of Mirador.

**Comment by gigamorph** [comment]
@csbailey5t Ok, that sounds good.

**Pull request merged**
