### PR TITLE
add basic gallery view to windows

### PR DESCRIPTION
**Pull request by aeschylus**
gallery view

### Acceptance Criteria
- [x] User can select "Gallery" from window topbar
  - [x] Uses CustomGalleryView SVG from #1947 
  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M19.974,2H2V19.974H19.974V2ZM7.392,18.177H3.8V14.582H7.392Zm0-5.392H3.8V9.19H7.392Zm0-5.392H3.8V3.8H7.392Zm5.392,10.785H9.19V14.582h3.595Zm0-5.392H9.19V9.19h3.595Zm0-5.392H9.19V3.8h3.595Zm5.392,10.785H14.582V14.582h3.595Zm0-5.392H14.582V9.19h3.595Zm0-5.392H14.582V3.8h3.595Z" transform="translate(1 1)"/></svg>`
  - [x] Wraps icon in MUI `<SvgIcon>` for theme-ability. See approach in #1967 used for other custom SVGs
- [x] Uses a vanilla HTML implementation (not something canvas-based, like [OSD Collection mode](https://openseadragon.github.io/examples/tilesource-collection/) per discussion with tech lead and design team) so that content will be keyboard navigable
- Clicking on a canvas
  - [x] Provides a visual indicator around selected canvas (see mockup)
  - [x] Updates `canvasIndex` 
  - [x] viewer stays in Gallery view (i.e. this is a departure from Mirador 2 gallery behavior)
- [x] Switching to an alternate view (single, book) opens to the selected canvas
- [ ] Add tests
## Questions @ggeisler @jvine 
- **"No selected canvas" UI State**  - In the [original ticket](https://github.com/ProjectMirador/mirador/issues/2032), there are some gifs that describe a state in which there is no selected canvas. At least as currently implemented, this state is never reached by the application. Do we still want to account for this?
- **Accessibility roles** - I added a `role="button"` to the gallery items, but I wasn't sure about further guidance on this. Could be ticketed elsewhere.
- **Caption Typography** - In its current state, I edited the caption typography. Not sure if we want to include that here or just remove the labels entirely. There are a few design considerations around how labels are elided, and how they affect the layout (especially the height) of the items in the view.
- **Layout Considerations** - There were quite a few layout considerations I ran into, and some manual testing and experimentations with various manifest types with disparate canvas aspect ratios would be useful. I ran into these kinds of things several years ago and wrote of some code and diagrams pertaining to them in [this repo](https://github.com/sul-dlss/iiif-layout-functions/blob/master/README.md). See also the issues for diagrams that contain more questions.

### CODE REVIEW

**Comment by aeschylus** [comment]
### Follow-on Tickets
- [ ] Update Typographic hierarchy to provide smaller captions
- [ ] Gallery View Label Styling
- [ ] Make Gallery View Properties Theme-able
- [ ] Gallery View Item Styling
- [ ] Gallery View Layout Improvements

**Comment by camillevilla** [comment]
Closes #2032. See spin out tickets above. https://github.com/ProjectMirador/mirador/pull/2154#issuecomment-472098370

**Comment by snydman** [comment]
Glad to see this merged. @ggeisler @jvine I note the departure from Mirador 2. That when a thumb in gallery view is clicked it takes the user to full view.  Aside from being a departure, it feels like expected behavior to go to the full view.  I believe the rationale is because gallery view will be a way of selecting multiple images for other advanced features.  Is that correct?  What is rationale for this change?

**Comment by jvine** [comment]
There were several requirements for gallery view that came out of user interviews, related to working with the images in that mode, rather than using it only as an alternate navigation tool. 

- enhance (greyscale, invert, etc), rotate, flip images in gallery view
- reorder images, either manually via drag-drop, or by sorting/filtering on metadata
- select images to open in new independent windows
- annotate / view annotations 
- toggle a specified layer on/off for all images
- zoom & pan the gallery

Obviously, these are mostly future features. But when we discussed where to start with gallery view in M3, we decided not to just replicate M2 as a navigation tool, but to show some of the functionality that's possible when it's a "working" view, parallel to Single and Book. At the moment, that just means being able to view and interact with the sidebar content (metadata, annotations, etc.) as you select or unselect an item in the Gallery. 

It also means that in order to show an image in Single/Book view, you have to select the image in Gallery view, then reset your view. 

We are looking into adding an additional action - a second click, a hover button, something discoverable but not noisy - to the image you have selected in the Gallery that will directly open it in your previous view (Book/Single).

**Pull request merged**
