### PR TITLE
Standardize icons to Sharp versions

### LINKED ISSUE #1947: Standardized icon set
Primarily using icons from the MUI "Sharp" theme: https://material.io/tools/icons/?search=left&icon=play_circle_outline&style=sharp

Custom icons are provided for some core features for M3 specificity, visual consistency, disambiguation with similar icons in the UI/alternate icon meanings. (svgs in comment below.)

Location | Icon
------------ | -------------
Workspace menu | @material-ui/icons/MenuSharp
Workspace fullscreen | @material-ui/icons/FullscreenSharp
Workspace fullscreen exit | @material-ui/icons/FullscreenExitSharp
Settings | @material-ui/icons/SettingsSharp
Share | @material-ui/icons/ShareSharp
Export | @material-ui/icons/SaveAltSharp
Window menu | @material-ui/icons/MoreVertSharp
Window maximize | **CustomWindowMax**
Window maximize exit | **CustomWindowMin**
Close (multiple locations) | @material-ui/icons/CloseSharp
Sidebar toggle | @material-ui/icons/MenuSharp
Tab - About | @material-ui/icons/InfoSharp
Tab - Index | **CustomIndex**
Tab - Search | @material-ui/icons/SearchSharp
Tab - Annotations | @material-ui/icons/CommentSharp
Tab - Layers | @material-ui/icons/LayersSharp
Open sidebar in panel | @material-ui/icons/OpenInNewSharp
Collapse toggle left | @material-ui/icons/ArrowLeftSharp
Collapse toggle right | @material-ui/icons/ArrowRightSharp
Expand content (within panel) | @material-ui/icons/ExpandMoreSharp
Collapse content (within panel) | @material-ui/icons/ExpandLessSharp
View - Single | @material-ui/icons/CropOriginalSharp
View -  Book | **CustomBookView**
View -  Scroll | **CustomScrollView**
View -  Gallery | **CustomGalleryView**
View -  Thumbs off | @material-ui/icons/CropDinSharp
View -  Thumbs bottom | **CustomThumbsBottom**
View -  Thumbs side | **CustomThumbsSide**
Canvas - Previous/Left | @material-ui/icons/PlayCircleOutlineSharp
Canvas - Next/Right | @material-ui/icons/PlayCircleOutlineSharp (rotate 180 degrees)
Canvas - Zoom in | @material-ui/icons/AddCircleOutlineSharp
Canvas - Zoom out | @material-ui/icons/RemoveCircleOutlineSharp
Canvas - Restore/Zoom to fit | **CustomRestoreZoom**
Error | @material-ui/icons/ErrorOutlineSharp
Drag | @material-ui/icons/DragIndicatorSharp

Custom icons | Image
------------ | -------------
CustomWindowMax | customwindowmax
CustomWindowMin | customwindowmin
CustomIndex | customindex
CustomBookView | custombookview
CustomScrollView | customscrollview
CustomGalleryView | customgalleryview
CustomThumbsBottom | customthumbsbottom
CustomThumbsSide | customthumbsside
CustomRestoreZoom | customrestorezoom

### PR DESCRIPTION
**Pull request by jkeck**
...and add a few custom Mirador specific icons

Closes #1947 

## Open Questions/TODOs (more details below):
- [x] Testing Icon components
  * We could test that, uh, react works, but not sure that's useful.  Should we ignore icons from coverage (assuming they won't have anything useful to be tested w/i them)?
- [x] Confirm that the icons in the `Replacement icons listed...` note below will all be implemented in future feature development
- [x] Determine if this PR should add custom icons for features that haven't been implemented yet (or let those features add them)
- [x] Confirm/fix list on Non Sharp icons (listed below)

---

icons

### Replacement icons listed in #1947 that aren't in the codebase yet
- Workspace fullscreen exit / `@material-ui/icons/FullscreenExitSharp`
  - We don't have an exit icon because the icon is not visible when in full screen
- Share / `@material-ui/icons/ShareSharp`
  - We don't have this feature yet
- Tab - Search / `@material-ui/icons/SearchSharp` 
  - We don't have this feature yet
- Tab - Annotations / `@material-ui/icons/CommentSharp` 
  - We don't have this feature yet
- Tab - Layers / `@material-ui/icons/LayersSharp` 
  - We don't have this feature yet
- Collapse toggle left / `@material-ui/icons/ArrowLeftSharp` 
  - I'm not sure what this is and/or we don't have this feature yet
- Collapse toggle right / `@material-ui/icons/ArrowRightSharp`
  - I'm not sure what this is and/or we don't have this feature yet
- Drag / `@material-ui/icons/DragIndicatorSharp`
  - I believe this is being added in #1961, however, it's not really a drag behavior right now, so not 100% sure if we should use this particular icon or not.  (thoughts @jvine?) 

### The features that would implement these icons do not exist
- Window maximize / CustomWindowMax
  - We don't have a Window Minimize/Maximize feature yet
- Window maximize exit / CustomWindowMin
  - We don't have a Window Minimize/Maximize feature yet
- View - Scroll / CustomScrollView
- View - Gallery / CustomGalleryView

### Non-Sharp Icons remaining
- Using Add and Clear icons in Workspace Add
- Using Loupe icon in Workspace Menu (toggle zoom controls)
- Using ViewHeadline in Workspace Menu (list all open windows)

### CODE REVIEW

**Comment by jvine** [comment]
>Workspace fullscreen exit / `@material-ui/icons/FullscreenExitSharp`
> * We don't have an exit icon because the icon is not visible when in full screen

I think this is a bug. The full application is going full screen; there's no reason the app sidebar should disappear. 

> * Collapse toggle left / `@material-ui/icons/ArrowLeftSharp`
>   * I'm not sure what this is and/or we don't have this feature yet
> * Collapse toggle right / `@material-ui/icons/ArrowRightSharp`
>   * I'm not sure what this is and/or we don't have this feature yet

This is the small tab that hides the sidebar without "closing" it. It hasn't been implemented yet.

screen shot 2019-02-26 at 9 36 32 am

> Drag / `@material-ui/icons/DragIndicatorSharp`
> * I believe this is being added in #1961, however, it's not really a drag behavior right now, so not 100% sure if we should use this particular icon or not.  (thoughts @jvine?)

I don't think this icon is directly needed yet. 

> * Using Add and Clear icons in Workspace Add

Add - missed this when I replaced something else. Should be AddSharp.
Clear - should be replaced by CloseSharp. It's the same icon; should use the same name.

> * Using Loupe icon in Workspace Menu (toggle zoom controls)

This should be removed; see #1936 

> * Using ViewHeadline in Workspace Menu (list all open windows)

This should be removed; see #1936

**Comment by jkeck** [comment]
Thanks @jvine.  I'll file an issue about changing the full screen behavior and make sure to explicitly mention the icon addition.

I've changed `Clear` to `CloseSharp` and `Add` to `AddSharp`.  All icons are now either Sharp, Custom, or will be removed in #1936.

**Comment by aeschylus** [comment]
I don't think it's useful to test the existence of the icons.

I also think that icons can be added as needed by new features as part of their acceptance criteria, or otherwise that another PR can be created to add all the icons we know we'll need soon.

**Comment by aeschylus** [comment]
Not sure what coverage we can possibly add here without writing meaningless tests, so I'm merging this.

**Pull request merged**
