### PR TITLE
Feature/2.1 search within

### PR DESCRIPTION
**Pull request by jeffreycwitt**
Just sending in an early pull request for search within. I think it should definitely still be considered a work in progress. But I think its worth getting wider feed back and design review before we take in much further.

(Don't be misled by branch name. By 2.1 we simply meant search within work built **on top of** 2.1 release branch)

### CODE REVIEW

**Comment by jbhoward-dublin** [comment]
Just to note: users will in some cases arrive at the viewer after executing a full-text search in a discovery environment; it will be useful to be able to pass search terms from that environment to Mirador so that the search is executed when the manifest is opened ... so, there should be an initialisation parameter that can be assigned search terms.

**Comment by dicksonlaw583** [comment]
Is this PR still under active development? It would be great to get search API integration into upcoming versions of Mirador, and we at University of Toronto are interested in integrating your additions. If you are ready but the test coverage drop is preventing it from being accepted, please let me know if I can help out with that.

**Comment by jeffreycwitt** [comment]
I think we're more or less waiting for a design review and discussion of the best ways to use the side panel. The search panel works as is, but it's just a matter of what its final integration should look like. I think it is definitely a priority for 2.2

**Comment by snydman** [comment]
Yes, this is a high priority.  It will need design review and test coverage support. Thanks for the offer to help @dicksonlaw583!  Now that M2.1 is released we'll make a firm plan for search at the next Mirador call.

**Comment by rsinghal** [comment]
Closing this so we can delete `release2.1`

**Comment by jbaiter** [comment]
> Closing this so we can delete release2.1

So what does this mean for the Search API within Mirador? Is the implementation in this PR not going to be merged? Or how can I understand that comment? :-)

**Comment by snydman** [comment]
@jbaiter - @jeffreycwitt and others submitted this PR as a WIP as a way to stimulate discussion and feedback on how to implement Search Within in Mirador.  And indeed what has followed has been a detailed discussion and design process to specify the implementation.  The current proposal, I believe, is for a small group of engineers to work on this in early 2017. It remains a high priority, just waiting for an engineering team to mobilize at the right moment to re-implement according to the new specification.  https://docs.google.com/document/d/1uvwgAvPGxhM94wYylMItSV6nd39V9uObd82NrjoDI9Y/edit?usp=sharing

**Pull request closed without merging**
