### PR TITLE
fix: fetchSearch

### PR DESCRIPTION
**Pull request by fstoe**
Hey,
i tried to fix this [issue](https://github.com/ProjectMirador/mirador/issues/3936).
It seems like the onSubmit sends two events. The first one being undefined and the second being the actual onSubmit one. This results in the dispatching of the `action fetchSearch` two times

### CODE REVIEW

**Review by marlo-longley — CHANGES_REQUESTED** [review]
Thank you for looking at this! I looked closer and noticed how the tests were failing. Here is what I came up with:

```
  submitSearch(event) {
    const {
      companionWindowId, fetchSearch, searchService, windowId,
    } = this.props;
    const { search } = this.state;
    if (!search) return;

    if (event && event.type === 'submit' && this.state.isSuggestionSelected) {
      event.preventDefault();
      return; // Do not trigger search again if a suggestion was selected
    }

    if (event) {
      event.preventDefault();
    }
    fetchSearch(windowId, companionWindowId, `${searchService.id}?${new URLSearchParams({ q: search })}`, search);
  }
  ```
  
  This approach requires adding something new to the component state (`isSuggestionSelected`), and also handling that elsewhere in the file (reset to false at the top of `handleChange`) and also in `selectItem`:
  ```
    selectItem(_event, selectedItem, _reason) {
    if (selectedItem && getMatch(selectedItem)) {
      this.setState({ search: getMatch(selectedItem), isSuggestionSelected: true }, this.submitSearch);
    }
  }
  ```

 That is just some ideas, it may not make sense overall but the tests are passing with that, and there are no double searches.

**Comment by fstoe** [comment]
Ah thanks for the input for fixing the tests and updated the `SearchPanelControls` with you're suggestions

**Comment by marlo-longley** [comment]
@fstoe nice! This seems to fix the double request bug for me and not break anything else, but I would be curious for someone else to test it out.

**Review by marlo-longley — DISMISSED** [review]

**Comment by fstoe** [comment]
> I'm curious if #3999 (rewriting these components to functions) fixes it or has the same problems.

I just tested but unfortunately the bug persists when using the functional component.

**Pull request merged**
