### PR TITLE
Replace old windows instead of reusing

### PR DESCRIPTION
**Pull request by aeschylus**

### CODE REVIEW

**Comment by aeschylus** [comment]
I have solved the bug, but at the expense of writing new integration tests, which I have not been able to get to run more than two event hops down. Would be very open to some help with that early tomorrow morning @mejackreed, @versae, @csbailey5t

**Comment by aeschylus** [comment]
This also does not completely solve the issue for the changeLayout function yet, but I am working on that now.

**Comment by mejackreed** [comment]
Is there an issue to link to here?

**Comment by csbailey5t** [comment]
This addresses #1159.

**Pull request merged**
