### PR TITLE
Test using jasmine-jquery matchers rather than string matching.

### PR DESCRIPTION
**Pull request by csbailey5t**
This PR addresses #1167, where 5 tests regularly failed due to a single space mismatch. Instead of using string comparison, the tests now use jasmine-jquery matches on the DOM. This PR does maintain the general approach to checking for preservation of the manifest order as the previous tests.

### CODE REVIEW

**Comment by csbailey5t** [comment]
@rsinghal Perhaps I don't understand how your initial tests worked then. It seemed like you were moving around the book 1 manifest when creating the new ManifestListItem, then in the expectedHTML checking for whether the ```li``` with the correct index contains the expected markup based on the book 1 address.

**Comment by csbailey5t** [comment]
Ah, I see it now. I think we just need to check the ```li``` structure now. If we're just testing index positioning, we don't actually need to check the book 1 uri at all.

**Comment by rsinghal** [comment]
I did this a while ago, so my memory is rusty.

I had to move around book1 (which corresponds to the id in `dummyManifest.json`) in order to get ManifestListItem to insert it at various spots within the `appendTo` section, since ManifestListItem gets the index based on the `data` array. So, given an existing set of `li` tags, would ManifestListItem insert it at the correct position depending on the index value of the manifest I'm inserting?  It would have been easier to just give ManifestListItem the index where it should be inserted, but I probably wrote that code that made it difficult to give that value, so I fudged it a bit by using the `data` array.

**Comment by rsinghal** [comment]
Yes, we just need to make sure all of the `data-index-number` values are correct after inserting the new manifest.

**Comment by csbailey5t** [comment]
@rsinghal I updated the code to actually check the order of the ```li``` elements, still using Jasmine rather than string matching. It's perhaps a bit indirect, but seems to now do both things the original tests did.

**Pull request merged**
