### PR TITLE
Configurable language

### PR DESCRIPTION
**Pull request by morpheus-87**
This PR makes the language of the UI configurable in the init step.

### CODE REVIEW

**Comment by aeschylus** [comment]
This has some conflicts with the improvements from one of your other PRs. Also, there is another way to implement configuration which is used in other areas of the app, so can you resubmit this as a new PR with that pattern? 

A good example can be found by looking at the [`saveController.js`](https://github.com/ProjectMirador/mirador/blob/2.1.4/js/src/utils/saveController.js) and the `DEFAULT_SETTINGS` in [`settings.js`](https://github.com/ProjectMirador/mirador/blob/2.1.4/js/src/settings.js)

Marking as wontfix for now, but open to a revised PR.

**Comment by morpheus-87** [comment]
I checked your change request and saw, that there is no other way to get configuration parameters in `viewer.js` except reading it from the state.

It seems, that the behaviour you are talking about, was removed in commit d0f6310 by @rsinghal.

**Comment by rsinghal** [comment]
That's the correct way to get information from the configuration @aeschylus.  Not sure what you are looking for?

**Comment by aeschylus** [comment]
Sorry, was closing like 12 PRs simultaneously and don't think I grasped what this was trying to do. If you need to get the configuration dynamically (rather than on initialisation of the whole App using extend), this makes sense.

Can you settle the conflict in viewer.js and we can merge from there?

**Comment by morpheus-87** [comment]
In the meantime, I fixed the conflict, @aeschylus.

**Comment by aeschylus** [comment]
Looks like viewer.js is still a stub, but that would be the place I think. You would need to test that the language was one thing in the config before the runtime initialisation.

Thanks for fixing this up. Looking forward to merging.

**Comment by morpheus-87** [comment]
Is is really necessary to have a separate testcase for setting the language, @aeschylus?

**Comment by aeschylus** [comment]
@morpheus-87 Always a fair question. I think it could be useful since it's happening at runtime. Can one of us help set up the test case?

**Comment by morpheus-87** [comment]
Would be great, if somebody could help me with setting up the test case.

**Comment by morpheus-87** [comment]
Could somebody help me with setting up the test case?

**Comment by rsinghal** [comment]
@morpheus-87 Hopefully this will help you set up the tests:

https://github.com/ProjectMirador/mirador/blob/detail_images_and_image_choice/spec/widgets/sidePanel.test.js

Specifically, this is to create a skeleton config: https://github.com/ProjectMirador/mirador/blob/detail_images_and_image_choice/spec/widgets/sidePanel.test.js#L17

And then this actually tests something that is in the config: https://github.com/ProjectMirador/mirador/blob/detail_images_and_image_choice/spec/widgets/sidePanel.test.js#L102

**Comment by morpheus-87** [comment]
I just updated the branch and set up a testcase in `spec/mirador.test.js`.

**Comment by aeschylus** [comment]
Thanks @morpheus-87. This looks good to me.

**Pull request merged**
