### PR TITLE
prefix action types

### PR DESCRIPTION
**Pull request by charbugs**
see #2931

### CODE REVIEW

**Comment by mejackreed** [comment]
I'm good with this. Is there anything else that needs to be done to account for point 3 in #2931 ?

Is there anything within [createSlice](https://redux-starter-kit.js.org/api/createslice/) that we could use? I haven't looked into that too much, but curious if you had.

**Comment by mejackreed** [comment]
One more minor thought.. is there anyway that this should be configurable as a setting? Would someone have multiple Mirador stores in the same application?

**Comment by charbugs** [comment]
> Is there anything else that needs to be done to account for point 3 in #2931

It's possible to work around this by providing a `createRootReducer` function similar to the one of Mirador, so it's not a blocker for integration with React/Redux. On the other hand it's not nice to do so, it could be more developer friendly. I think this is a good resource for this issue: https://redux.js.org/recipes/code-splitting

> One more minor thought.. is there anyway that this should be configurable as a setting? Would someone have multiple Mirador stores in the same application?

Good point. I think this shouldn't be so hard. I will check what's necessary for that

**Comment by charbugs** [comment]
Ok, it seems to be not that simple: 

If you run two instances of Mirador each with its own redux store than the action types will not conflict., so that's save I guess. Running two instances of Mirador with a shared store is not possible at the moment for at least two reasons:

1) The action types will conflict because of the same name (that's what was statet above)
2) You need different state slices for each Mirador instance, but Mirador expects its state at the root level (see point 3 of #2931)

Enabeling two Mirador instances in a React/Redux app requires some more work than this PR can do. So, this PR only solves the problem of name conflicts with the action types of the host application.

**Pull request merged**
