### PR TITLE
Stop using default props in BackgroundPluginArea

### PR DESCRIPTION
**Pull request by jcoyne**
defaultProps are deprecated for function components

### CODE REVIEW

**Review by marlo-longley — COMMENTED** [review]
Do we want to totally remove `propTypes` rather than leaving this?
```
BackgroundPluginArea.propTypes = {
  PluginComponents: PropTypes.array,
};
```

**Comment by cbeer** [comment]
I'm not sure I understand why we're dropping propTypes entirely. I don't see anything upstream about deprecating those, and a trivial test of the upstream pattern seems to work fine?

 https://github.com/ProjectMirador/mirador/pull/3976

**Comment by jcoyne** [comment]
@cbeer the prop-types library has been archived. It is no longer supported: https://github.com/facebook/prop-types

**Comment by cbeer** [comment]
Fixed in https://github.com/ProjectMirador/mirador/pull/3976.

**Pull request closed without merging**
