### PR TITLE
Feature/cspace fixes and layers work

### PR DESCRIPTION
**Pull request by radpet**

### CODE REVIEW

**Comment by rsinghal** [comment]
@radpet Can you break this PR down into smaller pieces?  The bug fixes need to be separate from new features.

**Comment by radpet** [comment]
@rsinghal check out the other pull request :) but you can cherry pick the latest fixes that are not in that branch from here

**Comment by csbailey5t** [comment]
@radpet Please do break down this PR (and #1361) into its component pieces, with each PR specifically targeting a bug or feature with reference to its Github issue. This sort of large PR, especially since it duplicates work in other PRs, such as #1306 and #1361, becomes difficult for maintainers to sort through and engage. It also problematizes focused conversation on specific code changes in the PR since it lumps together so many different things. Per the contributing guideslines, PRs are much more helpful if they target single matters of concern.

**Comment by radpet** [comment]
Yea I know this I can say I have contributed many things before but sadly this time I have no time to sort the things out for you so I give you the source code. The bugfixes are organized as commits to each pull request so you can cherry pick them for example. If you have any issues or questions feel free to ask me :)

**Comment by aeschylus** [comment]
After looking through the discussion above, I will close this for now. The work will still be available for future integration, so we can return to this when resourcing allows it to be broken down more. With so many threads going into the same work cycle, we need smaller PRs for quick merges. The [contributing guidelines](https://github.com/ProjectMirador/mirador/blob/develop/CONTRIBUTING.md#making-changes) suggest beginning with a discrete issue, and then submitting a PR to close the issue. I know this PR comes out of a longer bout of work with a wider scope, addressing a diverse set of use cases, and it will be good to have on file for when those get ticketed separately.

@radpet Thanks for the continuing contributions.

**Pull request closed without merging**
