### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mejackreed** [comment]
I'm seeing some issues with the deployed version here: https://deploy-preview-1988--mirador-dev.netlify.com/__tests__/integration/mirador/

```
TypeError: Object(...) is not a function
    at useTranslation (mirador.min.js?v=1551312177405:404)
    at I18nextWithTranslation (mirador.min.js?v=1551312177405:404)
    at Ag (mirador.min.js?v=1551312177405:282)
    at lh (mirador.min.js?v=1551312177405:282)
    at mh (mirador.min.js?v=1551312177405:282)
    at Ph (mirador.min.js?v=1551312177405:282)
    at Qh (mirador.min.js?v=1551312177405:282)
    at sh (mirador.min.js?v=1551312177405:282)
    at Uf (mirador.min.js?v=1551312177405:282)
    at Xh (mirador.min.js?v=1551312177405:282)
    at Yh (mirador.min.js?v=1551312177405:282)
    at ci.render (mirador.min.js?v=1551312177405:282)
    at mirador.min.js?v=1551312177405:282
    at Uh (mirador.min.js?v=1551312177405:282)
    at fi (mirador.min.js?v=1551312177405:282)
    at Object.render (mirador.min.js?v=1551312177405:282)
    at new MiradorViewer (mirador.min.js?v=1551312177405:404)
    at Object.viewer (mirador.min.js?v=1551312177405:404)
    at (index):13
```

**Comment by cbeer** [comment]
Weird; I'm not seeing that locally. Are you?

**Comment by mejackreed** [comment]
No I'm not. I've tried both development and production builds locally and cannot recreate the problem.

**Comment by cbeer** [comment]
Ugh.

**Pull request closed without merging**
