### PR TITLE
Added translatable collection dialog

### PR DESCRIPTION
**Pull request by DigitLib**
Added COLLECTION and CLOSE button translatable.

### CODE REVIEW

**Comment by mejackreed** [comment]
I'm not seeing these in the English translation file: https://github.com/ProjectMirador/mirador/blob/master/src/locales/en/translation.json

Can you say more about where these are used?

**Comment by DigitLib** [comment]
Here
image

Here
image

Serbian
image

**Comment by mejackreed** [comment]
Thank you! yes, I missed this completely. Could you please update to have them alphabetically sorted?

**Comment by DigitLib** [comment]
Done.

**Review by mejackreed — APPROVED** [review]
👏 thank you!

**Pull request merged**
