### PR TITLE
Add plugin hook to window menu. Closes #2298

### LINKED ISSUE #2298: Plugin hook in window menu
There should be a place in the window menu for plugin components. This place should only show up if a plugin wants to render a component there, otherwise it's not visible. I know there is design needed and generally we should come up with a concept for plugin UX stuff. But to move the plugin system forward and be able to demo it, it would be nice to have this simple plugin playground.

### PR DESCRIPTION
**Pull request by charbugs**
Please see #2298 

plugin-section-in-window-menu

### CODE REVIEW

**Comment by charbugs** [comment]
> we don't want to maintain targets for every possible plugin idea in code, but provide a generic method of adding plugins.

I agree with that in general and I wished there would be a generic solution for adding plugin components. But from what I understand so far there is no other *clean* solution for that. For deleting, replacing and wrapping components by plugins there are already generic methods in `withPlugins`. But *adding* a plugin component to the render tree of a target component always means that the target must treat the plugin explicitly.

Take for example this component:

```javascript
const TopBar = (props) => (
  <List>
    <Item>
      <MenuButton />
    </Item>
    <Item>
      <CloseButton />
    </Item>
  </List>
);
```

There is a generic solution to inject a plugin component into this render tree: You could target for example the `MenuButton` and render the plugin component as a sibling of it. This is what the original `miradorWithPlugins` function did. But there are two issues: a) To inject a plugin to `TopBar` you have to target the `MenuButton` (or another component of the render tree) and this is semantically messy. b) It will break the layout as the first Item now consists of `MenuButton` and the plugin component.

> What are the other target areas we are likely to create and how do we document and maintain them?

Unless we find another solution we indeed have to define and document plugin areas which I think souldn't be a big problem. There is another one I would like to implement: `BackgroundPluginArea`. This is a hidden component where plugins can add to which want to implement a feature without a visible UI component.

Can you give some additional explanations of your concerns? In which way could mainting be a problem here? Can you outline what plugin approach is used by Mirador 2?

**Comment by camillevilla** [comment]
Thanks for providing this seam, @charbugs. 

@aeschylus, I don't think this approach *prevents* the more generic approach  for adding plugins. I believe that as long as the component's container imports `withPlugins`, a plugin author would be able to add a seam there, right? 

I'm not sure if you're referring to prototype discussions or the meeting back in January, but I thought we agreed in January that we should provide at least one recommended plugin seam in the UI. The rationale was preventing UI pollution. I think this PR gives a nice incentive to plugin authors to develop towards this seam.

We're not there yet, but other seams that I can imagine coming down the pipeline:
- wherever image manipulation tools end up after #1985
- adding new types of companion windows

**Comment by cbeer** [comment]
> we don't want to maintain targets for every possible plugin idea in code, but provide a generic method of adding plugins.

I thought that was the pattern we were using; is the concern just that we don't want a `WindowPluginButtons` component, but we'd rather drop `PluginComponent` into `WindowTopMenu`
directly to remove some of the indirection?

I guess I'm with @camillevilla; this unblocks putting plugins in the window menu and when we get designs for how plugins should be displayed, it seems trivial to refactor.

**Comment by charbugs** [comment]
> is the concern just that we don't want a WindowPluginButtons component, but we'd rather drop PluginComponent into WindowTopMenu
directly to remove some of the indirection?

Right, that's better. I will change it.

One note for better understanding: Not all plugins need the *add* mode to place components to mirador. E.g. we in Leipzig want to provide our own WorkspaceAdd panel to enable a discovery service. In order to do that we will probably use the *replace* mode. This can of course be considered as adding a custom component, but technically it works differently. What I said in the comment above only applies to the *add* mode.

**Pull request merged**
