### PR TITLE
replace immutablejs by lodash

### PR DESCRIPTION
**Pull request by charbugs**
immutable is a realtive big library and we make only little use of it. any functions we use from immutable can be replaced by lodash and lodash/fp.

### CODE REVIEW

**Comment by charbugs** [comment]
Has someone an idea what the code climate check is trying to tell me?

**Comment by mejackreed** [comment]
I would be fine with ignoring the CodeClimate check.. it seems not relevant.

**Comment by charbugs** [comment]
ok, and what about the travis check? it shows a red cross above but the logs say: #8234 passed.

**Comment by mejackreed** [comment]
Maybe just a strange issue with travis. Thanks for moving this improvement forward @charbugs !!

**Pull request merged**
