### PR TITLE
Fix some typos in comments (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by aeschylus** [comment]
Hi Stefan, I had another look at this and it seems some of the spelling corrections were made to our dependencies. It is perhaps concerning that programmers don't always spell correctly, but I don't want to edit our dependencies in any way that might bother the build and dependency management system down the line. 

Would you please reverse those other spelling mistakes that occur on objects in the lib folder? If not, we can always close this request and do this on another branch.

**Comment by stweil** [comment]
@aeschylus, which files are you referring to? The PR does not include changes to files in a `lib` folder.

**Comment by rsinghal** [comment]
I think he is referring to the files in `css/plugins`.  Those are third party files, so we don't want to mess with them.

**Comment by stweil** [comment]
I removed the `css/plugins` related commit from the PR now.

**Pull request merged**
