### PR TITLE
Disable eslint prefer-default-export

### LINKED ISSUE #1707: Allow named exports
recommend changing the eslint rule to `"import/prefer-default-export": "off"`.  

The current convention of renaming the default export in the import statement (e.g.  `import ConnectedApp from '../components/App';`) smells.  named imports can and should be used wherever possible as this facilitates composition imports and potentially reduces bundle size for consumers.

### PR DESCRIPTION
**Pull request by christopher-johnson**
closes #1707

### CODE REVIEW

**Comment by cbeer** [comment]
Didn't @charbugs's work to separate containers resolve this?

**Comment by christopher-johnson** [comment]
no.

**Comment by mejackreed** [comment]
> The current convention of renaming the default export in the import statement (e.g. `import ConnectedApp from '../components/App';`) smells.

This seems resolved by @charbugs , no?

> named imports can and should be used wherever possible as this facilitates composition imports and potentially reduces bundle size for consumers.

Is this still true? Are there cases where when we have a single export we don't want it as the default export? I'm all for modifying our style guide approach, I would just like better understanding of why we are doing something.

**Comment by cbeer** [comment]
I guess I'm not seeing us rename the default export any more (`ConnectedXYZ`), hence my confusion.

**Comment by christopher-johnson** [comment]
sorry, I did not ref. https://github.com/ProjectMirador/mirador/issues/1862.  the reducers need to be named exports so that an implementation can create its rootReducer with them.

**Comment by charbugs** [comment]
It is not quite the same issue as \<ConnectedBlaBla/\>. Eslint complains if you only have a single named export. But there are cases where you want to do this.

**Pull request merged**
